#!/usr/bin/python36

import pymsteams, sys
from time import sleep

testing=''
zabbix_url='https://www.zabbix.com'

# Read Webhook URL from file
def read_url(filename):
    with open(filename) as f:
        return f.readline()


def get_url (filename):
    if len(sys.argv) < 2:
        print ("Reading from file.")
        global testing 
        testing = True
        return str(read_url(filename))
    else:
        return str(sys.argv[1])




teamsCard = pymsteams.connectorcard( get_url('./api_connector.url') )
teamsCard.color("#ff0000") # Alarm Color 

if testing == True: 
    print("Sending test Card...")
    teamsCard.title("Notification test")
    teamsCard.text("This alarm was generated by {}".format(sys.argv[0]))
    teamsCard.addLinkButton("Open zabbix", zabbix_url)
    print ("\n+++ CARD BEGIN ------------------------------------------------\n")
    teamsCard.printme()
    print ("\n+++ CARD END --------------------------------------------------\n")
    while True:
        try:
            print ("Sending Card")
            print (teamsCard.send())
        except pymsteams.Exception :
            
            continue
        print ("Card Sent.")
        break
        
else:
    #TODO implement dinamic cards for MS teams.
    pass


