#!/usr/bin/python36

import pymsteams, sys
from time import sleep

testing=''
zabbix_url='https://www.zabbix.com'



def read_url(filename):
    """ Reads a file an gets the first line from it.
    
    Parameter:

    filename (string): File name or file Path absolute or relative to current directory.

    Return:

    string:File first line
    """
    with open(filename) as f:
       return f.readline()
   


def get_url (filename=''):
    """ Get the url if no arguments had been passed to the script.
    
    Parameter:

    filename (string): File name or file Path absolute or relative to current directory.
    
    Return:
    
    string:URL of Webhook
    """
    if len(sys.argv) < 2:

        print ("Reading from file.")
        global testing 
        testing = True
        return str(read_url(filename))

    else:
        return str(sys.argv[1])

def send_card (card):
    """ Send teams card using card object.
    
    Parameter:

    card (connectorcard): Connector card ready to be sent.
    """

    while True:
        try:
            print ("Sending Card")
            if card.send():
                print ("Card Sent.")
            else:
                print ("Card Not Sent.")

        except pymsteams.TeamsWebhookException:
            print ("Trying again ")
            sleep(0.2)
            continue

        break


teamsCard = pymsteams.connectorcard(get_url('./webhook.url'))

if testing == True: 
    
    print("Sending test Card...")
    
    teamsCard.title("Notification test")
    teamsCard.text("This alarm was generated by {}".format(sys.argv[0].replace('_','\_')))
    teamsCard.addLinkButton("Open zabbix", zabbix_url)
    teamsCard.color("555555") # Unknown Color
    
    print ("\n+++ CARD BEGIN ------------------------------------------------\n")
    teamsCard.printme()
    print ("\n+++ CARD END --------------------------------------------------\n")
    
    send_card(teamsCard)

else:
    subject = sys.argv[2] 
    message = sys.argv[3]
    hostname = sys.argv[4]
    triggerid = sys.arg[5]
    eventid = sys.argv[6]
    
    #TODO Create a button with the trigger id if markdown link doesn`t work
    #TODO Create a prettier card with more integration like ACK and Comments to the Event.
    
    print("Building card.")
    teamsCard.title(subject + ' on ' + hostname)

    # Setting card color
    if subject == 'PROBLEM':
        teamsCard.color("EA4300")
    
    elif subject == 'RESOLVED':
        teamsCard.color("43EA00")
    
    else:
        teamsCard.color("555555")   

    teamsCard.text(message)
    send_card(teamsCard)


